services:
  readme.posts.postgres:
    image: postgres:14-alpine
    container_name: readme.posts.postgres
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    volumes:
      - ../../db/readme.posts.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - readme.posts

  readme.posts.pgadmin:
    image: dpage/pgadmin4
    container_name: readme.posts.pgadmin
    env_file:
      - ./.env.dev
    ports:
      - 8082:80
    depends_on:
      - readme.posts.postgres
    networks:
      - readme.posts

volumes:
  readme.posts.postgres:

networks:
  readme.posts:
    driver: bridge
