#Get create new user
POST http://0.0.0.0:3333/accounts/users
Content-Type: application/json

{
  "email": "user@notfound.local",
  "firstName": "John",
  "lastName": "Doe",
  "password": "123456"
}
###

# Change user's password
PATCH http://0.0.0.0:3333/accounts/users/6728dcb88404594068b2e846/password
Content-Type: application/json

{
  "password": "654321",
  "newPassword": "123456"
}
###
